# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [11]:
# Import torch
import torch

# Create random tensor

x = torch.rand(6,3,2,7)
y = torch.rand(1,4)
z = torch.rand(7)

print(x.ndim) #4
print(x.shape) #[6,3,2,7]

print(y.ndim) #2
print(y.shape) #[1,4]

print(z.ndim) #1
print(z.shape) #[7]

result = torch.rand(7,7)
print("\n\n ndim = ",result.ndim)
print("\n shape = ",result.shape)
print("\n",result)

4
torch.Size([6, 3, 2, 7])
2
torch.Size([1, 4])
1
torch.Size([7])


 ndim =  2

 shape =  torch.Size([7, 7])

 tensor([[0.7703, 0.9005, 0.1535, 0.3973, 0.7849, 0.0215, 0.7118],
        [0.7185, 0.7328, 0.8738, 0.0102, 0.0836, 0.7872, 0.0241],
        [0.8483, 0.3214, 0.8221, 0.2403, 0.8495, 0.6363, 0.2257],
        [0.5265, 0.4800, 0.3431, 0.4461, 0.5801, 0.1569, 0.0904],
        [0.6303, 0.4540, 0.6564, 0.7810, 0.1648, 0.8152, 0.8832],
        [0.5259, 0.2605, 0.4367, 0.1172, 0.2080, 0.7889, 0.6016],
        [0.5524, 0.3167, 0.5258, 0.3203, 0.4409, 0.3668, 0.1535]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [33]:
import torch

# Create another random tensor

A = torch.rand(3,7)
B = torch.rand(7,2)

print(A)
print(B)

# Perform matrix multiplication

# If input is a (n×m)(n×m) tensor, mat2 is a (m×p)(m×p) tensor, out will be a
# (n×p)(n×p) tensor.

Result = torch.C(A,B)
print("\n Dim = ",Result.ndim)
print("\n Shape = ", Result.shape)
print("\n AxB ",Result)


tensor([[0.1386, 0.2320, 0.7446, 0.5740, 0.5532, 0.2136, 0.3193],
        [0.5515, 0.9499, 0.7129, 0.6622, 0.6698, 0.4485, 0.1276],
        [0.9725, 0.0879, 0.2253, 0.3633, 0.4844, 0.8701, 0.9903]])
tensor([[0.2268, 0.3679],
        [0.5685, 0.8319],
        [0.7138, 0.1511],
        [0.9282, 0.4295],
        [0.1328, 0.8366],
        [0.8623, 0.2336],
        [0.5627, 0.5923]])

 Dim =  2

 Shape =  torch.Size([3, 2])

 AxB  tensor([[1.6649, 1.3048],
        [2.3362, 2.1259],
        [2.1405, 1.8160]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

La semilla manual en el contexto de generación de números aleatorios se refiere al valor inicial que se utiliza para inicializar el generador de números aleatorios. Cuando estableces una semilla manualmente utilizando torch.manual_seed(0) en PyTorch (o su equivalente en otras bibliotecas), estás fijando el generador de números aleatorios en un estado específico.

Esto es útil cuando se desea reproducibilidad en experimentos o cálculos que involucran elementos aleatorios. Al fijar la semilla, aseguras que el generador de números aleatorios produzca la misma secuencia de números aleatorios en cada ejecución del código. Esto es especialmente importante en el aprendizaje automático, donde a menudo se realizan experimentos y se ajustan modelos, y se desea que los resultados sean reproducibles.



In [43]:
import torch

# Set the random seed
torch.manual_seed(0)

# Generate random matrices A and B
A = torch.randn((7, 5))
B = torch.randn((5, 1))

# Perform matrix multiplication
C = torch.matmul(A, B)

print(C, C.size())


tensor([[-0.3287],
        [ 0.6325],
        [ 1.0654],
        [ 0.7772],
        [ 1.2944],
        [ 0.4913],
        [ 0.9247]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [60]:
# Set random seed on the GPU
import torch

'''
  Sets the seed for generating random numbers for the current GPU. It’s safe to
  call this function if CUDA is not available; in that case, it is silently
  ignored.
'''

if torch.cuda.is_available():
  print("Cuda availible")
  torch.cuda.manual_seed(1234)

torch.manual_seed(1234)

A = torch.randn((7, 5))

print(A)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539],
        [ 0.6684, -0.0597, -0.4675, -0.2153,  0.8840],
        [-0.7584, -0.3689, -0.3424, -1.4020,  0.3206],
        [-1.0219,  0.7988, -0.0923, -0.7049, -0.9340],
        [-0.5675, -0.2772, -2.1834,  0.3668,  0.7667],
        [ 0.0190,  0.0220, -1.1567,  1.8409, -1.0174],
        [ 1.2192,  0.1601, -0.6857, -0.0496, -1.2485]])



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [15]:
import torch

# Set random seed

torch.manual_seed(1234)

# Check for access to GPU

if torch.cuda.is_available():
  device = torch.device('cuda:0')

# Create two random tensors on GPU

  A = torch.randn(2,3).to(device)
  B = torch.randn(2,3).to(device)
  print(A)
  print(B)

tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]], device='cuda:0')
tensor([[ 0.2310,  0.6931, -0.2669],
        [ 2.1785,  0.1021, -0.2590]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [22]:
# Perform matmul on tensor_A and tensor_B

print(A)

#print(B)
B_reshaped = B.reshape(3,2)
print(B_reshaped)

result = torch.matmul(A,B_reshaped)

print("\n Result",result)


tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]], device='cuda:0')
tensor([[ 0.2310,  0.6931],
        [-0.2669,  2.1785],
        [ 0.1021, -0.2590]], device='cuda:0')

 Result tensor([[-0.2000,  1.1706],
        [ 0.2649, -1.3140]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [24]:
# Find max
print(result.max())

# Find min
print(result.min())

tensor(1.1706, device='cuda:0')
tensor(-1.3140, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max
print(result.argmax())

# Find arg min
print(result.argmin())


tensor(1, device='cuda:0')
tensor(3, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [26]:
import torch

# Set seed
torch.manual_seed(7)

# Create random tensor
A = torch.randn(1,1,1,10)

# Remove single dimensions
B = torch.randn(10)


# Print out tensors and their shapes

print(A,A.shape,A.ndim)
print(B,B.shape,B.ndim)

tensor([[[[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908, -0.8948, -0.3556,
            1.2324,  0.1382, -1.6822]]]]) torch.Size([1, 1, 1, 10]) 4
tensor([0.3177, 0.1328, 0.1373, 0.2405, 1.3955, 1.3470, 2.4382, 0.2028, 2.4505,
        2.0256]) torch.Size([10]) 1
